### ISSUE TITLE
[Bug]: CJKPDFReader InvalidURL in 0.8.62

### ISSUE THREAD

**Issue by AkimParis** [run-llama/llama-hub#623]
### Bug Description

Hello guys,

On update 0.8.62, I am not able to load the CJKPDFReader due to an "InvalidURL" on the library.json file. The version 0.8.61 is working perfectly. It's probably just a tiny typo between the name CJKPDFReader and cjk_pdf. Thx! 

### Version

0.8.62

### Steps to Reproduce

from pathlib import Path
from llama_index import download_loader

CJKPDFReader = download_loader("CJKPDFReader")
loader = CJKPDFReader()
documents = loader.load_data(file=Path('./article.pdf'))

### Relevant Logs/Tracbacks

```shell
<ipython-input-8-07687184dbaf> in <cell line: 4>()
      2 from llama_index import download_loader
      3 
----> 4 CJKPDFReader = download_loader("CJKPDFReader")
      5 loader = CJKPDFReader()
      6 

    444         if not host:
--> 445             raise InvalidURL(f"Invalid URL {url!r}: No host supplied")
    446 
    447         # In general, we want to try IDNA encoding the hostname if the string contains

InvalidURL: Invalid URL 'https:/raw.githubusercontent.com/run-llama/llama-hub/main/llama_hub/library.json': No host supplied
```

**Comment by CerealNotFound** [comment]
It runs into the same problem with WikipediaReader too

**Comment by anoopshrma** [comment]
Hi, could you try with the latest version. I just checked and I was able to create the loader instance for `CJKPDFReader`

**Comment by AkimParis** [comment]
@anoopshrma Yep, it's working on the version 0.8.63-post2. Thx! : )

**Comment by anoopshrma** [comment]
Awesome! 
@CerealNotFound  could you also check if it is working for you as well with the latest version.

**Comment by anoopshrma** [comment]
Bump @CerealNotFound !

**Comment by CerealNotFound** [comment]
@anoopshrma Got busy with smth else, gonna tell you by today :)

**Comment by CerealNotFound** [comment]
@anoopshrma Yup, it works fine! Thanks!

**Comment by anoopshrma** [comment]
> @anoopshrma Yup, it works fine! Thanks!

Awesome!! Since this issue has been resolved. I'm closing this issue. Feel free to open it if you face the issue!!
