### ISSUE TITLE
[Bug]: ImportError: cannot import name 'SitemapReader' from 'llama_hub.web.sitemap'

### ISSUE THREAD

**Issue by heldrida** [run-llama/llama-hub#632]
### Bug Description

Regarding llama-hub packages, finding an empty package after install llama-hub. More specifically, the sitemap package __init__.py is empty.

```
ImportError: cannot import name 'SitemapReader' from 'llama_hub.web.sitemap' (/opt/homebrew/lib/python3.11/site-packages/llama_hub/web/sitemap/__init__.py)
```

Where the file content is empty as follows:

```sh
cat /opt/homebrew/lib/python3.11/site-packages/llama_hub/web/sitemap/__init__.py
```

Output is:

```
```

Installed by:

```sh
pip3 install llama-hub
```

Source https://github.com/run-llama/llama-hub/tree/main/llama_hub/web/sitemap

### Version

0.8.68

### Steps to Reproduce

1) Install llama-hub
2) Import via the documented steps:

```
from llama_hub.web.sitemap import SitemapReader
```

**Comment by anoopshrma** [comment]
Hi, yes the init file is empty. Meanwhile you can import the reader like this for now.

`from llama_hub.web.base.sitemap import SitemapReader`

**Comment by anoopshrma** [comment]
Hey @heldrida,  your import should work now. Just upgrade llama-hub

`pip install --upgrade llama-hub`

**Comment by anoopshrma** [comment]
Did you get a chance to check on this @heldrida ?

**Comment by anoopshrma** [comment]
I'm closing this issue @heldrida, This has been fixed! 

If you still face this issue, feel free to open this again!
