### ISSUE TITLE
[Question]: An error occurred (301) when calling the HeadObject operation: Moved Permanently

### ISSUE THREAD

**Issue by karan00713** [run-llama/llama-hub#634]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

When i gave my credentials in S3 Loader, it returned "An error occurred (301) when calling the HeadObject operation: Moved Permanently" This error? is this because of the wrong endpoint? how to fix this?

**Comment by biocar2001** [comment]
same problem

**Comment by karan00713** [comment]
It solved, it because of the wrong endpoint i gave, mine was ap-south-1
