### ISSUE TITLE
[Bug]: llama pack StreamlitChat: RuntimeError

### ISSUE THREAD

**Issue by pjaskulski** [run-llama/llama-hub#657]
### Bug Description

After correcting the error from ticket #656 and starting the application, an error appears after entering the first question in the chat: 

`RuntimeError: There is no current event loop in thread 'ScriptRunner.scriptThread'`

Looking for answers, I came across this thread: [llama_index issue 7244](https://github.com/run-llama/llama_index/issues/7244)
after applying the advice from dosubot (using asyncio) the problem disappears, the chat starts to work correctly.

### Version

0.9.7

### Steps to Reproduce

1. download the llama pack StreamlitChat, run, enter the query in the chat field and run.

### Relevant Logs/Tracbacks

```shell
2023-11-25 18:35:21.904 Uncaught app exception
Traceback (most recent call last):
  File "/home/piotr/ihpan/gpt-4-turbo/venv/lib/python3.8/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 534, in _run_script
    exec(code, module.__dict__)
  File "/home/piotr/ihpan/llamaindex_test/streamlit_chatbot/base.py", line 136, in <module>
    StreamlitChatPack(run_from_main=True).run()
  File "/home/piotr/ihpan/llamaindex_test/streamlit_chatbot/base.py", line 108, in run
    response = st.session_state["chat_engine"].stream_chat(selected)
  File "/home/piotr/ihpan/gpt-4-turbo/venv/lib/python3.8/site-packages/llama_index/callbacks/utils.py", line 39, in wrapper
    return func(self, *args, **kwargs)
  File "/home/piotr/ihpan/gpt-4-turbo/venv/lib/python3.8/site-packages/llama_index/chat_engine/context.py", line 201, in stream_chat
    chat_response = StreamingAgentChatResponse(
  File "<string>", line 10, in __init__
  File "/usr/lib/python3.8/asyncio/queues.py", line 35, in __init__
    self._loop = events.get_event_loop()
  File "/usr/lib/python3.8/asyncio/events.py", line 639, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'ScriptRunner.scriptThread'.
```

**Comment by carolinedlu** [comment]
Hey @pjaskulski, thanks for sharing this! What version of Streamlit are you using?

**Comment by tonykipkemboi** [comment]
Hey @pjaskulski, I am submitting a PR to fix this atm. In the meantime,  add the `asyncio` event loop at the top like so:
```python
from typing import Dict, Any
import asyncio

# Create a new event loop
loop = asyncio.new_event_loop()

# Set the event loop as the current event loop
asyncio.set_event_loop(loop)

from llama_index import (
    VectorStoreIndex,
    ServiceContext,
    download_loader,
)
from llama_index.llama_pack.base import BaseLlamaPack
from llama_index.llms import OpenAI
```

**Comment by pjaskulski** [comment]
> Hey @pjaskulski, thanks for sharing this! What version of Streamlit are you using?

1.20

**Comment by pjaskulski** [comment]
> Hey @pjaskulski, I am submitting a PR to fix this atm. In the meantime, add the `asyncio` event loop at the top like so:

Thanks!

**Comment by tonykipkemboi** [comment]
@pjaskulski, let me know if you're still seing the error.

**Comment by pjaskulski** [comment]
@tonykipkemboi it's ok now, after adding asyncio it starts working properly.

**Comment by tonykipkemboi** [comment]
Great! The PR is merged as well so this issue should be good to close.
