### ISSUE TITLE
[Feature Request]: Sharepoint Loader Support in LlamaHub

### ISSUE THREAD

**Issue by arun-soliton** [run-llama/llama-hub#674]
### Feature Description

1. Similar to Microsoft One_drive, Sharepoint Data Loader is needed.

### Reason

As a company, we are currently using Microsoft Apps for everything. We have our documents in Sharepoints and currently downloading and using manually using `SimpleDirectoryReader`. To make it fully automated, a Sharepoint Loader is required. 

### Value of Feature

Building end-to-end ETL pipeline in an automated way.

**Comment by anoopshrma** [comment]
That will be awesome addition to llama-hub! 

Would you like to contribute on this. That will be great!!

**Comment by anoopshrma** [comment]
Awesome!!

**Comment by arun-soliton** [comment]
@anoopshrma closing this Since the feature is merged into `llama_hub`
