### ISSUE TITLE
[Feature Request]: Ollama Query Engine Pack

### ISSUE THREAD

**Issue by shauryr** [run-llama/llama-hub#677]
### Feature Description

Ollama is a great way of hosting models locally. It would be great if we can have a Ollama pack just like the zephyr query engine pack. Ollama makes it easy to swap out and try different open source models.

**Comment by anoopshrma** [comment]
https://llamahub.ai/l/llama_packs-ollama_query_engine?from=all


I hope this solves this issue 🙂. If so mind closing this issue.

Thanks!

**Comment by shauryr** [comment]
Thank you so much!!
