### ISSUE TITLE
[Feature Request]: integration with Snowflake

### ISSUE THREAD

**Issue by khire12** [run-llama/llama-hub#749]
### Feature Description

Hi I wanted to know if there is any plan on a loader for Snowflake data warehouse like the database loader. It will be really helpful to integrate snowflake with llamaindex. Currently I am just downloading data/ loading in pandas dataframe and then using it with llamaindex.

**Comment by anoopshrma** [comment]
@godwin3737  to your rescue: https://llamahub.ai/l/snowflake?from=all

If this solves your issue, mind closing this issue?
