### ISSUE TITLE
[Feature Request]: Conversational Memory in Llamaindex

### ISSUE THREAD

**Issue by ankitajdesai** [run-llama/llama-hub#763]
### Feature Description

I am generating a chatbot using llama-hub for the company knowledge-base. It is working perfectly fine, but not maintaining any context or reference for previous answer. e.g. What is reminder rule will be answer perfectly, but then how to set it will not be answer as it is not having reference of previous answer.

### Reason

LlamaIndex is generating an Index and there is no way to pass that ConversationalRetrievalChain or ConversationalEntityMemory. 

### Value of Feature

It will be very easy for anyone to build chatbot that exactly work like chatbot, but on customized knowledgebase.

**Comment by anoopshrma** [comment]
Hey, did you take a look at chat engine in llamaindex
https://docs.llamaindex.ai/en/stable/module_guides/deploying/chat_engines/root.html

**Comment by anoopshrma** [comment]
Let me know if this helped you @ankitajdesai 
So that I can close this issue 🙂

**Comment by anoopshrma** [comment]
Hey @ankitajdesai , 
I'm closing this issue, if you still have any doubt you can re open this issue anytime or raise a new one 🙂

**Comment by ankitajdesai** [comment]
Hello,

Sorry for the delayed response, but yeah that has solved my requirement.
