### ISSUE TITLE
[Documentation]: Typo in "langchain" example code snippet of Graph Database Cypher Loader

### ISSUE THREAD

**Issue by ZGChung** [run-llama/llama-hub#785]
### Documentation Issue Description

On the page [Graph Database Cypher Loader of Llama Hub](https://llamahub.ai/l/graphdb_cypher), the proposed example code snippet to transform the document to "langchain" document contains a typo. 

"to_lang**h**chain_format()" should be "to_langchain_format()"

### Documenation Link

https://llamahub.ai/l/graphdb_cypher

**Comment by logan-markewich** [comment]
Just pushed a fix for this in the UI
