### ISSUE TITLE
[Feature Request]: Loader Idea  - Github Integration

### ISSUE THREAD

**Issue by mwolfson** [run-llama/llama-hub#789]
### Feature Description

It would be extremely powerful to be able to clone a repository, and use that as RAG source.

I am not super sophisticated, and perhaps this can be done myself if I look into the tool further (so apologies if this feature request is naive).

**Comment by mwolfson** [comment]
Dug a little deeper into the repo, and see this is being worked on, so I am deleting this request.

**Comment by mwolfson** [comment]
Looks like this is already being worked on.

**Comment by anoopshrma** [comment]
Yeah, we have https://llamahub.ai/l/github_repo?from=loaders for using it as a RAG source. 

If this works for you, Mind If I close this request?
