### ISSUE TITLE
[Documentation]: Reference to llama-packs vs llama-pack

### ISSUE THREAD

**Issue by danlemont** [run-llama/llama-hub#832]
### Documentation Issue Description

The sample code references "llama-packs" (plural), but should reference "llama-pack".  It should be updated from:

from llama_index.llama_packs import download_llama_pack

to

from llama_index.llama_pack import download_llama_pack

### Documenation Link

https://llamahub.ai/l/llama_packs-snowflake_query_engine?from=all

**Comment by anoopshrma** [comment]
Ah I see, Thanks for highlighting this. 


Would you be interested to fix this?

**Comment by danlemont** [comment]
Thanks Anoop.  PR submitted.
