### ISSUE TITLE
[Feature Request]: Linkedin integration

### ISSUE THREAD

**Issue by racso-dev** [run-llama/llama-hub#903]
### Feature Description

Would be amazing to have a loader for linkedin profiles

### Value of Feature

This feature would be valuable for anyone that is building on top of Linkedin's profiles data.
My usecase is to build a RAG over Linkedin profiles and a position criteria, It would be extremely usefull to have a Linkedin loader instead of having to scrape that data manually.

**Comment by kishan2k2** [comment]
https://www.linkedin.com/help/linkedin/answer/a1341387#:~:text=In%20order%20to%20protect%20our,automate%20activity%20on%20LinkedIn's%20website.
